In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
base_path = ''
pd.set_option('display.max_row', 600)

In [2]:
# 제품목록 gds_list_0, gds_list_1
gds_2 = pd.read_csv(base_path + 'gds2.csv')

# 제품 카테고리 목록: gdsclss_list_0, gdsclss_list_1
gdsclss_2 = pd.read_csv(base_path + 'gdsclss_2.csv')

# 매출 데이터 마스터(장바구니 단위): tr_list_0, tr_list_1
tr_list_2 = pd.read_csv(base_path + 'tr_list_2.csv')

# 매출 제품 데이터 상세: tr_dtl_list_0, tr_dtl_list_1
tr_dtl_list_2 = pd.read_csv(base_path + 'tr_dtl_list_2.csv')

C:\Users\min\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (2,9,11) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
C:\Users\min\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [3]:
gds_2

CO_CD  STR_CD         PLU_CD     GDS_NM  GDS_CLSS_CD GDS_TP_NM  \
0       1001294   12018              1        배송비       999999       배송료   
1       1001294   12018              2     사은행사쿠폰       999999       배송료   
2       1001294   12018          91770     코지유리물병        93331        일반   
3       1001294   12018          91770       크지물병        91701        일반   
4       1001294   12018       50390427      POM석류        12579        일반   
...         ...     ...            ...        ...          ...       ...   
172730  1002056  168009  9805817760205        포카칩       898989        일반   
172731  1002056  168009  9808205106111  매입에서등록한상품       997979        일반   
172732  1002056  168009  9808862878406        월드콘       898989        일반   
172733  1002056  168009  9880913160015  매입에서등록한상품       997979        일반   
172734  1002056  168009       99889906     버디 토스트       898989        일반   

        VEN_CD  
0            0  
1            0  
2            0  
3            0  
4            0  
...        ...  
172730      46  
172731      30  
172732       9  
172733      34  
172734    8989  

[172735 rows x 7 columns]

In [4]:
gdsclss_2

CO_CD  STR_CD  GDS_CLSS_CD GDS_CLSS_NM  GDS_CLSS_LVL_TP  \
0     1001294   12018            1          식품                1   
1     1001294   12018          101       가공농산물                2   
2     1001294   12018        10151       가공농산물                3   
3     1001294   12018        10152         김치류                3   
4     1001294   12018        10153          소스                3   
...       ...     ...          ...         ...              ...   
1134  1002056       0           99         미등록                1   
1135  1002056       0         9979   임시핸디매입등록용                2   
1136  1002056       0       997979   임시핸디매입등록용                3   
1137  1002056       0         9999         미등록                2   
1138  1002056       0       999999         미등록                3   

      UP_GDS_CLSS_CD  GDS_CLSS_GRP_TP  
0                  0                1  
1                  1                1  
2                101                1  
3                101                1  
4                101                1  
...              ...              ...  
1134               0                1  
1135              99                1  
1136            9979                1  
1137              99                1  
1138            9999                1  

[1139 rows x 7 columns]

In [5]:
tr_list_2

SAL_DT  STR_CD POS_NO  TRAN_NO SALE_KIND_TP_NM  SALE_RTN_SGN  \
0        20210901   12018     01        1            영업개시             1   
1        20210901   12018     01        2             준비금             1   
2        20210901   12018     01        3              매출             1   
3        20210901   12018     01        4            전체취소             1   
4        20210901   12018     01        5              매출             1   
...           ...     ...    ...      ...             ...           ...   
1551504  20220901  168009      1      284              매출             1   
1551505  20220901  168009      1      285            캐셔정산             1   
1551506  20220901  168009      1      286           POS정산             1   
1551507  20220901  168009      1      287            영업종료             1   
1551508  20220901  168009      1      288             로그인             1   

         REAL_SAL_DT  REAL_SAL_TTM    PAY_AMT   MSHP_ID  ORN_SAL_DT  \
0           20210901         65745        0.0       NaN         NaN   
1           20210901         65758        0.0       NaN         NaN   
2           20210901         71138  9000000.0       NaN         NaN   
3           20210901         85353        0.0       NaN         NaN   
4           20210901         91245     3650.0  012018_0         NaN   
...              ...           ...        ...       ...         ...   
1551504     20220901        143610     1900.0       NaN         NaN   
1551505     20220901        143805        0.0       NaN         NaN   
1551506     20220901        143811        0.0       NaN         NaN   
1551507     20220901        143812        0.0       NaN         NaN   
1551508     20220901        143840        0.0       NaN         NaN   

        ORN_POS_NO  ORN_TRAN_NO  
0              NaN          NaN  
1              NaN          NaN  
2              NaN          NaN  
3              NaN          NaN  
4              NaN          NaN  
...            ...          ...  
1551504        NaN          NaN  
1551505        NaN          NaN  
1551506        NaN          NaN  
1551507        NaN          NaN  
1551508        NaN          NaN  

[1551509 rows x 13 columns]

In [6]:
tr_dtl_list_2

SAL_DT  STR_CD POS_NO  TRAN_NO  SEQ_NO DESI_CNCL_TP_NM  \
0        20210901   12018     01        3       1            정상판매   
1        20210901   12018     01        3       2            정상판매   
2        20210901   12018     01        3       3            정상판매   
3        20210901   12018     01        3       4            정상판매   
4        20210901   12018     01        3       5            정상판매   
...           ...     ...    ...      ...     ...             ...   
6521910  20220901  168009      1      282       4            정상판매   
6521911  20220901  168009      1      282       5            정상판매   
6521912  20220901  168009      1      283       1            정상판매   
6521913  20220901  168009      1      284       1            정상판매   
6521914  20220901  168009      1      284       2            정상판매   

         SALE_RTN_SGN         PLU_CD  GDS_CLSS_CD  SALE_QTY  SALE_PRC  \
0                   1  8801039939499      12301.0     180.0    3000.0   
1                   1  8801045312316      12101.0     360.0    1000.0   
2                   1  8801045291314      12101.0     360.0    1000.0   
3                   1  8803712127018      11363.0     180.0    2700.0   
4                   1  8801045890333      12102.0     180.0    9500.0   
...               ...            ...          ...       ...       ...   
6521910             1  2504010000015      40101.0       1.0    3000.0   
6521911             1  8809730783199     999999.0       1.0    1000.0   
6521912             1  8801056020026     898989.0       1.0     500.0   
6521913             1  4711269689931     999999.0       6.0     200.0   
6521914             1  8801045520117     999999.0       1.0     700.0   

          SALE_AMT SGDS_DC_TP_NM  SGDS_DC_PRC  SUBTOT_DC_AMT  EVT_DC_AMT  \
0         540000.0          할인특매          0.0            0.0         0.0   
1         360000.0          할인특매          0.0            0.0         0.0   
2         360000.0          할인특매          0.0            0.0         0.0   
3         486000.0          할인특매          0.0            0.0         0.0   
4        1710000.0          할인특매          0.0            0.0         0.0   
...            ...           ...          ...            ...         ...   
6521910     3000.0            정상          0.0            0.0         0.0   
6521911     1000.0            정상          0.0            0.0         0.0   
6521912      500.0            정상          0.0            0.0         0.0   
6521913     1200.0            정상          0.0            0.0         0.0   
6521914      700.0            정상          0.0            0.0         0.0   

         CPON_DC_AMT SCALES_GDS_TP_NM  GDS_CPON_DC_AMT  BASKET_CPON_DC_AMT  
0                0.0               일반              0.0                 0.0  
1                0.0               일반              0.0                 0.0  
2                0.0               일반              0.0                 0.0  
3                0.0               일반              0.0                 0.0  
4                0.0               일반              0.0                 0.0  
...              ...              ...              ...                 ...  
6521910          0.0               일반              0.0                 0.0  
6521911          0.0               일반              0.0                 0.0  
6521912          0.0               일반              0.0                 0.0  
6521913          0.0               일반              0.0                 0.0  
6521914          0.0               일반              0.0                 0.0  

[6521915 rows x 20 columns]

In [30]:
df['STR_CD'].unique()

array([ 12018,  72005, 142011, 168009], dtype=int64)

In [31]:
df['STR_CD'].nunique()

4

In [32]:
df['CO_CD'].unique()

array([1001294, 1001739, 1001993, 1002056], dtype=int64)

In [33]:
df['PLU_CD'].unique()

array([            1,             2,         91770, ..., 9808862878406,
       9880913160015,      99889906], dtype=int64)

In [34]:
df['PLU_CD'].nunique()

121632

In [35]:
df['GDS_NM'].unique()

array(['배송비', '사은행사쿠폰', '코지유리물병', ..., '전국관광지도', '수수마당비', '버디 토스트'],
      dtype=object)

In [36]:
df['GDS_NM'].nunique()

134452

In [37]:
df['GDS_CLSS_CD'].unique()

array([999999,  93331,  91701,  12579,  12855,  11509,  20901,  90601,
        91201,  11365,  11660,  11664,  94101,  91106,  80299,  10151,
        99999,  11271,  11167,  12101,  93330, 140101,  11261,  11502,
        12001,  93551,  29999,  20101,  21102,  11166,  21001,  11801,
        12203,  22502,  95001,  12574,  12212,  11366,  22501,  11899,
        11514, 960299,  93334,  11266,  11272,  12883,  11270,  11273,
        89999,  91107,  12581,  11362,  11173,  11599,  52699,  92901,
        91901,  20104,  95101,  11506,  20102,  11262,  11360,  12550,
        91103,  40199,  40207,  11260,  22503,  91102,  12901,  12991,
        90302,  91101,  94537,  11505,  90301,  11663,  30499,  90201,
        19999,  90101,  11067,  20601,  12770, 129999,  11165,  12204,
        59999,  11361,  12205,  30502,  10402,  22001,  49999,  91117,
        93441,  30699,  93332,  39999,  11171,  11060,  29901,  79999,
        10401,  10303,  12992,  30202,  30299,  30702,  30701,  30101,
      

In [38]:
df['GDS_CLSS_CD'].nunique()

549

In [7]:
df = pd.DataFrame(gds_2)
print(df)

          CO_CD  STR_CD         PLU_CD     GDS_NM  GDS_CLSS_CD GDS_TP_NM  \
0       1001294   12018              1        배송비       999999       배송료   
1       1001294   12018              2     사은행사쿠폰       999999       배송료   
2       1001294   12018          91770     코지유리물병        93331        일반   
3       1001294   12018          91770       크지물병        91701        일반   
4       1001294   12018       50390427      POM석류        12579        일반   
...         ...     ...            ...        ...          ...       ...   
172730  1002056  168009  9805817760205        포카칩       898989        일반   
172731  1002056  168009  9808205106111  매입에서등록한상품       997979        일반   
172732  1002056  168009  9808862878406        월드콘       898989        일반   
172733  1002056  168009  9880913160015  매입에서등록한상품       997979        일반   
172734  1002056  168009       99889906     버디 토스트       898989        일반   

        VEN_CD  
0            0  
1            0  
2            0  
3            0  
4 

In [8]:
duplicateDFRow = df[df.duplicated()]

In [9]:
print(duplicateDFRow)

          CO_CD  STR_CD        PLU_CD                  GDS_NM  GDS_CLSS_CD  \
161     1001294   12018     980080005                   누텔라앤고        11509   
182     1001294   12018   19891020059             바이스125MM(5)        90601   
205     1001294   12018   27000380765                 헌트 토마토홀       140101   
213     1001294   12018   29000073258          플랜터스 드라이넛 피넛보틀        12001   
263     1001294   12018   38900004651              파인애플(청크/돌)       140101   
270     1001294   12018   40000201328                스니커즈미니어쳐        11509   
292     1001294   12018   41716230077                프리고스트링치즈        12574   
311     1001294   12018   51000027962               프레고프레쉬머쉬룸        11271   
372     1001294   12018   71160161870             MB-(대접시)110        93334   
377     1001294   12018   71160161924              MB-(공기)426        93334   
401     1001294   12018   72810772149                 리고 초코시럽        11266   
441     1001294   12018   80432402733                   시바스리갈   

In [10]:
df[df['GDS_NM'] == '누텔라앤고']

CO_CD  STR_CD      PLU_CD GDS_NM  GDS_CLSS_CD GDS_TP_NM  VEN_CD
10     1001294   12018   980080005  누텔라앤고        11509        일반       0
161    1001294   12018   980080005  누텔라앤고        11509        일반       0
72186  1001739   72005  9800800056  누텔라앤고        10101        일반      34

In [11]:
df[df['GDS_NM'] == '바이스125MM(5)']

CO_CD  STR_CD       PLU_CD       GDS_NM  GDS_CLSS_CD GDS_TP_NM  VEN_CD
23   1001294   12018  19891020059  바이스125MM(5)        90601        일반       0
182  1001294   12018  19891020059  바이스125MM(5)        90601        일반       0

In [12]:
df[df['GDS_NM'] == '헌트 토마토홀']

CO_CD  STR_CD       PLU_CD   GDS_NM  GDS_CLSS_CD GDS_TP_NM  VEN_CD
36   1001294   12018  27000380185  헌트 토마토홀       140101        일반      74
37   1001294   12018  27000380765  헌트 토마토홀       140101        일반      74
203  1001294   12018  27000380109  헌트 토마토홀        11599        일반      49
205  1001294   12018  27000380765  헌트 토마토홀       140101        일반      74

In [13]:
df[df['GDS_NM'] == '플랜터스 드라이넛 피넛보틀']

CO_CD  STR_CD       PLU_CD          GDS_NM  GDS_CLSS_CD GDS_TP_NM  \
45   1001294   12018  29000073258  플랜터스 드라이넛 피넛보틀        12001        일반   
213  1001294   12018  29000073258  플랜터스 드라이넛 피넛보틀        12001        일반   

     VEN_CD  
45       35  
213      35

In [14]:
df[df['GDS_NM'] == '파인애플(청크/돌)']

CO_CD  STR_CD       PLU_CD      GDS_NM  GDS_CLSS_CD GDS_TP_NM  VEN_CD
76   1001294   12018  38900004651  파인애플(청크/돌)       140101        일반       0
263  1001294   12018  38900004651  파인애플(청크/돌)       140101        일반       0

In [15]:
df[df['GDS_NM'] == '스니커즈미니어쳐']

CO_CD  STR_CD       PLU_CD    GDS_NM  GDS_CLSS_CD GDS_TP_NM  VEN_CD
80   1001294   12018  40000201328  스니커즈미니어쳐        11509        일반       0
270  1001294   12018  40000201328  스니커즈미니어쳐        11509        일반       0
271  1001294   12018  40000668022  스니커즈미니어쳐        11509        일반       0

In [16]:
df[df['GDS_NM'] == '프리고스트링치즈']

CO_CD  STR_CD       PLU_CD    GDS_NM  GDS_CLSS_CD GDS_TP_NM  VEN_CD
91   1001294   12018  41716230077  프리고스트링치즈        12574        일반       0
292  1001294   12018  41716230077  프리고스트링치즈        12574        일반       0

In [17]:
df[df['GDS_NM'] == '프레고프레쉬머쉬룸']

CO_CD  STR_CD       PLU_CD     GDS_NM  GDS_CLSS_CD GDS_TP_NM  VEN_CD
101  1001294   12018  51000027962  프레고프레쉬머쉬룸        11271        일반      49
311  1001294   12018  51000027962  프레고프레쉬머쉬룸        11271        일반      49

In [18]:
df[df['GDS_NM'] == 'MB-(대접시)110']

CO_CD  STR_CD       PLU_CD       GDS_NM  GDS_CLSS_CD GDS_TP_NM  VEN_CD
121  1001294   12018  71160161870  MB-(대접시)110        93334        일반       0
372  1001294   12018  71160161870  MB-(대접시)110        93334        일반       0

In [19]:
df[df['GDS_NM'] == 'MB-(공기)426']

CO_CD  STR_CD       PLU_CD      GDS_NM  GDS_CLSS_CD GDS_TP_NM  VEN_CD
124  1001294   12018  71160161924  MB-(공기)426        93334        일반       0
377  1001294   12018  71160161924  MB-(공기)426        93334        일반       0

In [20]:
df[df['GDS_NM'] == '리고 초코시럽']

CO_CD  STR_CD       PLU_CD   GDS_NM  GDS_CLSS_CD GDS_TP_NM  VEN_CD
133  1001294   12018  72810772149  리고 초코시럽        11266        일반      49
401  1001294   12018  72810772149  리고 초코시럽        11266        일반      49

--------

In [21]:
df1 = pd.DataFrame(gdsclss_2)

In [22]:
duplicateDFRow1 = df1[df1.duplicated()]

In [23]:
print(duplicateDFRow1)

Empty DataFrame
Columns: [CO_CD, STR_CD, GDS_CLSS_CD, GDS_CLSS_NM, GDS_CLSS_LVL_TP, UP_GDS_CLSS_CD, GDS_CLSS_GRP_TP]
Index: []
